path:
  RAW_DATA_PATH: "./data/raw/"
  PROCESSED_DATA_PATH: "./data/processed/"

dataloader:
  dataset: "./data/raw/promoters.data"
  test_size: 0.25
  shuffle: True
  random_state: 42
  preprocess: False
  features_type: ["single", "di", "tri", "tetra", "GC"]

